default:
  username: guimsmendes
  password: 123456
quarkus:
  mongodb:
    connection-string: mongodb://localhost:27017
    database: quarkus-governance
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:default
      max-size: 16
      min-size: 0
  hibernate-orm:
    dialect: org.hibernate.dialect.H2Dialect
    database:
        generation: drop-and-create
  log:
    level: INFO
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] %L (%t) %s%e%n"
  console:
    color: true

"%test%":
  quarkus:
    log:
      level: DEBUG