version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy: 
    jobs:
      - build-and-test
      - create-image:
          requires: 
          - build-and-test
      - deploy:
          requires: 
          - create-image
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: make package
      - run:
          name: Test
          command: make test
  create-image:       
    docker:
      - image: cimg/openjdk:11.0
      - image: docker:17.05.0-ce-git
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: make docker-image-build
      - run:
          name: Push to Registry
          command: make push-image
  deploy:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - run:
          name: Deploy
          command: make deploy
