version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  github-cli: circleci/github-cli@1.0.4

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: quarkus
      DOCKER_IMAGE_NAME: ${CIRCLE_USERNAME}/${CIRCLE_PROJECT_REPONAME}
    docker:
      - image: cimg/openjdk:11.0
      - image: docker:17.05.0-ce-git

workflows:
  heroku_deploy: 
    jobs:
      - build-and-test
      - create-image:
          requires: 
          - build-and-test
      - deploy:
          requires:
          - create-image
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: make package
      - run:
          name: Test
          command: make test
  create-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: make build-image IMAGE_NAME=$IMAGE_NAME
      - run:
          name: Publish on DockerHub
          command: make push-image DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME IMAGE_NAME=$IMAGE_NAME USERNAME=$CIRCLE_USERNAME DOCKER_TOKEN=$DOCKER_ACCESS_TOKEN
  deploy:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run: heroku container:login
      - run:
          name: Push image to Registry
          command: make push-image-registry DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME
      - run:
          name: Deploy
          command: make deploy DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME REPO_NAME=$CIRCLE_PROJECT_REPONAME


      

