version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy: 
    jobs:
      - build-and-test
      - create-image:
          requires: 
          - build-and-test
      - deploy:
          requires: 
          - create-image
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: make package
      - run:
          name: Test
          command: make test
  create-image:       
    docker:
      - image: cimg/openjdk:11.0
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker Image
          command: make docker-image-build
  deploy:
    docker:
      - image: cimg/openjdk:11.0
      - image: docker:17.05.0-ce-git
    steps:
      - heroku/install
      - run: heroku container:login
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web
